<?php

namespace app\models;

use yii\db\ActiveRecord;

class Image extends ActiveRecord
{
    public function rules()
    {
        return [['title', 'unique']];
    }

    public static function tableName(): string
    {
        return "{{image}}"; // TODO: Change the autogenerated stub
    }
}